export interface GameEntry {
  id: string;
  title: string;
  slug: string;
  coverImage: string;
  backgroundImage: string;
  platform: string;
  hoursPlayed: number;
  completed: boolean;
  difficulty: string;
  rating: number;
  releaseYear: number;
  genre: string;
  favoriteAspect: string;
  description: string;
  accentColor: string;
}

export const GAMES: GameEntry[] = [
  {
    id: 'tlou1',
    title: 'The Last of Us Part I',
    slug: 'tlou1',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Last_of_Us_Part_I_cover.jpg',
    backgroundImage: 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Last_of_Us_Part_I_cover.jpg',
    platform: 'PC',
    hoursPlayed: 15,
    completed: true,
    difficulty: 'Survivor',
    rating: 10,
    releaseYear: 2013,
    genre: 'Survival Horror',
    favoriteAspect: 'The father-daughter dynamic between Joel and Ellie.',
    description: 'A benchmark for narrative-driven gameplay and emotional storytelling mechanics.',
    accentColor: '#4a7c4e',
  },
  {
    id: 'tlou2',
    title: 'The Last of Us Part II',
    slug: 'tlou2',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/4f/TLOU_P2_Box_Art_2.png',
    backgroundImage: 'https://upload.wikimedia.org/wikipedia/en/4/4f/TLOU_P2_Box_Art_2.png',
    platform: 'PC',
    hoursPlayed: 25,
    completed: true,
    difficulty: 'Survivor',
    rating: 10,
    releaseYear: 2020,
    genre: 'Survival Horror',
    favoriteAspect: 'The dual-perspective narrative that forces empathy.',
    description: 'Unparalleled technical achievement in animation and complex character writing.',
    accentColor: '#3d6b42',
  },
  {
    id: 're2',
    title: 'Resident Evil 2 Remake',
    slug: 're2',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Resident_Evil_2_Remake.jpg',
    backgroundImage: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Resident_Evil_2_Remake.jpg',
    platform: 'PC',
    hoursPlayed: 12,
    completed: true,
    difficulty: 'Hardcore',
    rating: 9,
    releaseYear: 2019,
    genre: 'Survival Horror',
    favoriteAspect: 'Relentless Mr. X pressure and perfect resource tension.',
    description: 'Masterful survival horror atmosphere with perfectly balanced resource management.',
    accentColor: '#c0392b',
  },
  {
    id: 're3',
    title: 'Resident Evil 3 Remake',
    slug: 're3',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/Resident_Evil_3.jpg',
    backgroundImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/Resident_Evil_3.jpg',
    platform: 'PC',
    hoursPlayed: 8,
    completed: true,
    difficulty: 'Nightmare',
    rating: 8,
    releaseYear: 2020,
    genre: 'Survival Horror',
    favoriteAspect: 'Nemesis encounters and the dodge mechanic.',
    description: 'High-octane survival with action-oriented cinematic set pieces.',
    accentColor: '#922b21',
  },
  {
    id: 're4',
    title: 'Resident Evil 4 Remake',
    slug: 're4',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/df/Resident_Evil_4_remake_cover_art.jpg',
    backgroundImage: 'https://upload.wikimedia.org/wikipedia/en/d/df/Resident_Evil_4_remake_cover_art.jpg',
    platform: 'PC',
    hoursPlayed: 20,
    completed: true,
    difficulty: 'Professional',
    rating: 10,
    releaseYear: 2023,
    genre: 'Survival Horror',
    favoriteAspect: 'Knife parry system and Ashley escort rebalancing.',
    description: 'Exceptional hardware optimization scaling and masterclass pacing.',
    accentColor: '#b7312c',
  },
  {
    id: 're7',
    title: 'Resident Evil 7: Biohazard',
    slug: 're7',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Resident_Evil_7_cover_art.jpg',
    backgroundImage: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Resident_Evil_7_cover_art.jpg',
    platform: 'PC',
    hoursPlayed: 10,
    completed: true,
    difficulty: 'Madhouse',
    rating: 9,
    releaseYear: 2017,
    genre: 'Survival Horror',
    favoriteAspect: 'First-person perspective completely reinventing the franchise.',
    description: 'The pinnacle of survival horror tension and first-person atmosphere.',
    accentColor: '#7d3c98',
  },
  {
    id: 're8',
    title: 'Resident Evil Village',
    slug: 're8',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/2c/Resident_Evil_Village.png',
    backgroundImage: 'https://upload.wikimedia.org/wikipedia/en/2/2c/Resident_Evil_Village.png',
    platform: 'PC',
    hoursPlayed: 12,
    completed: true,
    difficulty: 'Village of Shadows',
    rating: 9,
    releaseYear: 2021,
    genre: 'Survival Horror',
    favoriteAspect: 'Lady Dimitrescu and the castle atmosphere.',
    description: 'Excellent graphical atmosphere. Shadows of Rose expansion cleared.',
    accentColor: '#6c3483',
  },
  {
    id: 're9',
    title: 'Resident Evil 9: Requiem',
    slug: 're9',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/15/Resident_Evil_Requiem_Cover_Art.jpg',
    backgroundImage: 'https://upload.wikimedia.org/wikipedia/en/1/15/Resident_Evil_Requiem_Cover_Art.jpg',
    platform: 'PC',
    hoursPlayed: 14,
    completed: true,
    difficulty: 'Standard',
    rating: 8,
    releaseYear: 2025,
    genre: 'Survival Horror',
    favoriteAspect: 'The evolution of campaign structure and new survival mechanics.',
    description: 'Analyzed the latest evolution in campaign systems and survival mechanics.',
    accentColor: '#d35400',
  },
  {
    id: 'genshin',
    title: 'Genshin Impact',
    slug: 'genshin',
    coverImage: 'https://cdn1.epicgames.com/spt-assets/99dc46c68ea14324964a856d18dcac5b/genshin-impact-hqdph.jpg',
    backgroundImage: 'https://cdn1.epicgames.com/spt-assets/99dc46c68ea14324964a856d18dcac5b/genshin-impact-hqdph.jpg',
    platform: 'PC',
    hoursPlayed: 300,
    completed: true,
    difficulty: 'Spiral Abyss F36',
    rating: 8,
    releaseYear: 2020,
    genre: 'Open World RPG',
    favoriteAspect: 'Chapter VI Snezhnaya arc and elemental reaction depth.',
    description: "Chapter VI: Snezhnaya arc clear. Analyzing high-overhead rendering optimizations for the Khaenri'ah transition.",
    accentColor: '#1a78c2',
  },
  {
    id: 'ghost',
    title: 'Ghost of Tsushima',
    slug: 'ghost',
    coverImage: 'https://image.api.playstation.com/vulcan/ap/rnd/202010/0222/b3iB2zf2xHj9shC0XDTULxND.png',
    backgroundImage: 'https://image.api.playstation.com/vulcan/ap/rnd/202010/0222/b3iB2zf2xHj9shC0XDTULxND.png',
    platform: 'PC',
    hoursPlayed: 40,
    completed: true,
    difficulty: 'Lethal',
    rating: 10,
    releaseYear: 2020,
    genre: 'Action Adventure',
    favoriteAspect: 'The wind-guided traversal and the haiku system.',
    description: 'A cinematic open world masterpiece. The director\'s cut is a benchmark for environmental storytelling and fluid samurai combat.',
    accentColor: '#e67e22',
  },
  {
    id: 'valorant',
    title: 'Valorant',
    slug: 'valorant',
    coverImage: 'https://www.riotgames.com/darkroom/1200/1dbd7211e78ce5faa7a8af9d10afad47:2b5979e3922758399ba389561e797919/ps-f2p-val-console-launch-16x9.jpg',
    backgroundImage: 'https://www.riotgames.com/darkroom/1200/1dbd7211e78ce5faa7a8af9d10afad47:2b5979e3922758399ba389561e797919/ps-f2p-val-console-launch-16x9.jpg',
    platform: 'PC',
    hoursPlayed: 500,
    completed: false,
    difficulty: 'Diamond',
    rating: 9,
    releaseYear: 2020,
    genre: 'Tactical FPS',
    favoriteAspect: 'The precision gunplay layered with ability-based strategy.',
    description: 'High-ceiling tactical shooter. Agent ability systems analyzed for mechanical synergy and map control optimization.',
    accentColor: '#ff4655',
  },
];
